table HB_Date_Basic
	lineageTag: 03050478-8f42-4ab5-8029-9589fe29249a

	column DimDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4d0e1fef-e16a-4c89-8dc5-104de1a6e155
		summarizeBy: none
		sourceColumn: DimDate

		variation Variation
			isDefault
			relationship: 7c1a33d8-5ea9-4f2c-b769-fb60620cbace
			defaultHierarchy: LocalDateTable_be51dae9-07a1-4184-93b6-e114e1bdd3cf.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column WeekStart
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0956f901-dbb3-4994-8aac-3ad56ced3631
		summarizeBy: none
		sourceColumn: WeekStart

		variation Variation
			isDefault
			relationship: fcaa3fe0-ce6f-4f23-9cb9-c98e943f6eb1
			defaultHierarchy: LocalDateTable_138b723d-d93e-4058-9167-7c267b3696d2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: string
		lineageTag: 31fc7e47-a593-4d15-8763-45113e1f67ff
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column MonthStart
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5e575dfa-3c49-46c3-834b-685ff3f6565e
		summarizeBy: none
		sourceColumn: MonthStart

		variation Variation
			isDefault
			relationship: e0b72e55-f896-428f-b76a-b57f78429dfe
			defaultHierarchy: LocalDateTable_f07212e3-44b3-4f32-9850-8222fa3e11d6.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition HB_Date_Basic = m
		mode: import
		source =
				let
				
				   x = Number.From(DateTime.LocalNow())-Number.From(#date(2025, 6, 1)),
				
				   Source = List.Dates(#date(2025, 6, 1), x, #duration(1, 0, 0, 0)),
				
				   #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				
				   #"Changed Type" = Table.TransformColumnTypes(#"Converted to Table",{{"Column1", type date}}),
				
				   #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Column1", "DimDate"}}),
				    #"Added Custom" = Table.AddColumn(#"Renamed Columns", "WeekStart", each Date.StartOfWeek([DimDate], Day.Monday)),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "MonthStart", each Date.StartOfMonth([DimDate])),
				    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "Year", each Date.Year([DimDate])),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom2",{{"WeekStart", type date}, {"MonthStart", type date}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

